spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      #jdbc-url: jdbc:mariadb://localhost:3306/nerf?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      jdbc-url: jdbc:mariadb://mariadb:3306/nerf?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      connection-test-query: SELECT NOW() FROM dual


server:
  port: 3389

mybatis:
  configuration:
    map-underscore-to-camel-case: true


logging:
  pattern:
    dateformat: yyyy-MM-dd'T'HH:mm:ss.SSS,Asia/Seoul
